### ISSUE TITLE
PS1 and PS2 file names

### ISSUE THREAD

**Issue by SAB82** [pmanko/kdt_output_stripper#4]
Hi,
The file naming format that I was told to use by the sleep core for PS1 and PS2 files looks like this:
3339GX_2MAD_1-24_Ch_C3 Mx_PS1.PS1  or
3339GX_2MAD_1-24_Ch_C3 Mx_PS2.PS2
It would be great if we could somehow get the files to export in this format. This is not a huge deal as long as I get a chance to re-name them beforehand.

**Comment by pmanko** [comment]
@SAB82 Where is the best place to find the file name pattern? Should I use the pattern from the PASCI files in the generated PS1? What does each part of the file name mean?

**Comment by SAB82** [comment]
example: "3227GX_2MAD_WP3-24_Ch_C3 Ax_PS2.PS2" translates to
"Subcode_2 second Manual Artifact Detection_Wake periods contained in this file_Channel name as taken from PASCI file (includes and underscore in it)_File type.File type" Letme know if you have any questions.

**Comment by pmanko** [comment]
Closed with commit 25c5355.
