### ISSUE TITLE
Too many files error

### ISSUE THREAD

**Issue by SAB82** [pmanko/kdt_output_stripper#5]
So the reason that I broke the study up into 2 portions (3-24) (24-38) is because VP output stripper cannot handle more than ~250 files without crashing at the final stage of analysis in the program. It would be helpful to have a feature that allows me to generate a certain number of files for each PS1 and PS2 for each subject. This is a really great application and I am happy with the way everything else has been working so far.

**Comment by pmanko** [comment]
Closed with commit a732762.
